version: "3.3"
services:
  web:
    restart: "always"
    image: "brettalcox/tesla-inventory:2.9.0"
    ports:
      - "8080:8080"
    environment:
      US_M3SRPRWD: <url>
      US_M3LRAWD: <url>
      US_M3LRAWDP: <url>
      US_MYLRAWD: <url>
      US_MYLRAWDP: <url>
      US_MSPLAID: <url>
      US_MS100DE: <url>
      US_UNKNOWN: <url>
      CA_M3SRPRWD: <url>
      CA_M3LRAWD: <url>
      CA_M3LRAWDP: <url>
      CA_MYLRAWD: <url>
      CA_MYLRAWDP: <url>
      CA_MSPLAID: <url>
      CA_MS100DE: <url>
      CA_UNKNOWN: <url>
      ERROR_NOTIFICATION_URL: <url>
  redis:
    restart: "always"
    image: "redis:latest"
    ports:
      - "6379:6379"
  maria:
    restart: "always"
    image: "mariadb:10.5.12"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toot69
      MYSQL_DATABASE: inventory
    volumes:
      - /opt/mysql_data:/var/lib/mysql