version: "3.3"
services:
  web:
    restart: "always"
    image: "brettalcox/tesla-inventory:arm-2.8.2"
    ports:
      - "8080:8080"
  redis:
    restart: "always"
    image: "redis:latest"
    ports:
      - "6379:6379"
  maria:
    restart: "always"
    image: "jsurf/rpi-mariadb:latest"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toot69
    volumes:
      - /opt/mysql_data:/var/lib/mysql