version: "3.9"
services:
  web:
    restart: "always"
    image: "brettalcox/tesla-inventory:1.1.0"
    ports:
      - "8080:8080"
  redis:
    restart: "always"
    image: "redis:latest"
    ports:
      - "6379:6379"