tesla:
  inventory-with-pictures-url: https://tesla-info.com/for-sale.php
  detailed-inventory-url: https://tesla-info.com/inventory.php
  job-templates:
    -
      sale: New
      model: M3
      variant: SR
      minYear: 2021
      maxYear: 2021
      country: US
      sort: PA
      min: 0
      max: 99999999
      notification-url: ${NOTIFICATION_URL}
    -
      sale: New
      model: M3
      variant: LR
      minYear: 2021
      maxYear: 2021
      country: US
      sort: PA
      min: 0
      max: 99999999
      notification-url: ${NOTIFICATION_URL}
    -
      sale: New
      model: M3
      variant: Perf
      minYear: 2021
      maxYear: 2021
      country: US
      sort: PA
      min: 0
      max: 99999999
      notification-url: ${NOTIFICATION_URL}
  error-notification-url: ${ERROR_NOTIFICATION_URL}
cache:
  names:
    inventory: 900
    error: 60
    last-seen: 86400
spring:
  redis:
    host: redis
server:
  port: 8080
  servlet:
    context-path: /tesla-inventory-service